# Generated by Django 2.1.1 on 2018-09-20 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dongia_app', '0002_dong'),
    ]

    operations = [
        migrations.CreateModel(
            name='DongRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('paid', models.BooleanField(blank=True, null=True)),
                ('for_dong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_dong', to='dongia_app.Dong')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='dongia_app.User')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='dongia_app.User')),
            ],
        ),
    ]
