# Generated by Django 2.1.1 on 2018-09-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dongia_app', '0005_remove_dongrecord_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dongrecord',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='dongia_app.User'),
        ),
    ]
